#!/usr/bin/env python3
"""Governance audit for FSFFL future-pick economics.

This audit is intentionally non-production. It does not fit or change pick values.
It verifies that current external-market anchors are distinguished from heuristic
fallback/strategic transforms, and that the latter remain non-authoritative until
validated on temporally comparable evidence.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT = DATA / "audit"
OUT.mkdir(parents=True, exist_ok=True)

ENGINE = ROOT / "script" / "build_fsffl_gm_engine.py"
REGISTRY = DATA / "model_parameter_registry.json"
PICK_QUALITY = DATA / "pick_quality_model.json"
READINESS = OUT / "pick_outcome_readiness_audit.json"

MODEL_VERSION = "FSFFL-Future-Pick-Governance-1.0"


def load_json(path: Path, default=None):
    if not path.exists():
        return default
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def marker(text: str, pattern: str) -> bool:
    return re.search(pattern, text, flags=re.MULTILINE | re.DOTALL) is not None


def main():
    src = ENGINE.read_text(encoding="utf-8")
    registry = load_json(REGISTRY, {}) or {}
    pickq = load_json(PICK_QUALITY, {}) or {}
    readiness = load_json(READINESS, {}) or {}

    params = {p.get("id"): p for p in registry.get("parameters", [])}
    governed = params.get("PICK-MODEL-001", {})

    detected = {
        "external_market_pick_detection": "infer_fc_pick_values" in src,
        "fallback_same_year_tier_multipliers": marker(src, r'\{"early":\s*1\.18,\s*"mid":\s*1\.0,\s*"late":\s*0\.84\}'),
        "fallback_nearest_year_discount": "0.88 ** max(0, year - y0)" in src,
        "fallback_round_mid_anchors": all(x in src for x in ("1: 5200.0", "2: 2350.0", "3: 1050.0")),
        "fallback_calendar_discount_table": all(x in src for x in ("2027: 1.0", "2028: 0.88", "2029: 0.77")),
        "fallback_tier_adjustment": marker(src, r'\{"early":\s*1\.20,\s*"mid":\s*1\.0,\s*"late":\s*0\.82\}'),
        "quality_strength_horizon_weights": "dynasty_weight = clamp(0.48 + 0.08 * (years_out - 1), 0.48, 0.68)" in src,
        "quality_collapse_mix": "(1.0 - strength) * 0.72 + fragility * 0.28" in src,
        "quality_early_late_transform": all(x in src for x in ("0.10 + 0.58 * collapse_risk", "0.10 + 0.58 * strength")),
        "liquidity_constants": all(x in src for x in ("first_round_pick_liquidity", "second_round_pick_liquidity", "third_round_pick_liquidity")),
        "uncertainty_adds_optionality": "option = clamp(upside + 0.18 * clamp(uncertainty, 0.0, 1.0)" in src,
        "own_pick_control_bonus": "control_bonus = 0.10 if original_uid" in src,
        "future_utility_mix": "future_utility = clamp(0.62 * option + 0.38 * q" in src,
    }

    picks = pickq.get("picks", []) if isinstance(pickq, dict) else []
    horizon_groups = {}
    for p in picks:
        if not isinstance(p, dict):
            continue
        key = (p.get("original_roster_id"), p.get("round"))
        horizon_groups.setdefault(key, []).append(p)

    invariant_groups = 0
    comparable_groups = 0
    for rows in horizon_groups.values():
        rows = [r for r in rows if r.get("horizon_seasons") in (1, 2, 3)]
        if len({r.get("horizon_seasons") for r in rows}) < 2:
            continue
        comparable_groups += 1
        triples = {
            (
                round(float(r.get("early_scenario_weight") or 0), 3),
                round(float(r.get("mid_scenario_weight") or 0), 3),
                round(float(r.get("late_scenario_weight") or 0), 3),
            )
            for r in rows
        }
        if len(triples) == 1:
            invariant_groups += 1

    readiness_allowed = bool(
        readiness.get("finding", {}).get("authoritative_empirical_claim_allowed", False)
    )

    findings = [
        {
            "id": "PICK-ANCHOR-FALLBACK-001",
            "severity": "HIGH",
            "status": "PROVISIONAL_FALLBACK_ACTIVE",
            "observation": (
                "The engine correctly prefers directly observed FantasyCalc pick values when available, "
                "but missing cells fall through to hand-set tier multipliers, nearest-year discounting, "
                "round anchors and calendar discounts. These preserve functionality but are not empirical "
                "FSFFL pick economics."
            ),
            "evidence_tier": "EVIDENCE_BASED_EXTERNAL_ANCHOR for detected market cells; ASSUMPTION_SENSITIVE_PROVISIONAL for fallback cells",
            "authoritative_incremental_adjustment_claim_allowed": False,
        },
        {
            "id": "PICK-QUALITY-SCENARIO-001",
            "severity": "HIGH",
            "status": "HEURISTIC_SCENARIO_TRANSFORM_ACTIVE",
            "observation": (
                "Original-team strength, fragility, horizon weighting and early/mid/late scenario probabilities "
                "are generated by fixed transforms. They are scenarios, not calibrated probabilities, until "
                "time-ordered pick-slot prediction demonstrates calibration and ranking skill."
            ),
            "authoritative_probability_claim_allowed": False,
        },
        {
            "id": "PICK-HORIZON-UNCERTAINTY-001",
            "severity": "MEDIUM",
            "status": "HORIZON_UNCERTAINTY_NOT_EMPIRICALLY_IDENTIFIED",
            "observation": (
                f"The current pick-quality artifact has {invariant_groups} exactly invariant multi-horizon "
                f"original-team/round groups out of {comparable_groups} comparable groups. More generally, "
                "the scenario transform changes current-vs-dynasty strength weighting with horizon but has no "
                "validated forecast-error calibration showing how pick-slot uncertainty should broaden with time."
            ),
            "invariant_multi_horizon_groups": invariant_groups,
            "comparable_multi_horizon_groups": comparable_groups,
            "authoritative_uncertainty_claim_allowed": False,
        },
        {
            "id": "PICK-OPTIONALITY-001",
            "severity": "HIGH",
            "status": "UNCERTAINTY_REWARDED_BY_HEURISTIC",
            "observation": (
                "The utility layer adds a positive fraction of modeled uncertainty to pick optionality. Positive "
                "skew and liquidity can have economic value, but forecast uncertainty is not itself evidence of "
                "positive expected value. Outcome uncertainty, market liquidity and option value must be "
                "estimated or validated separately to avoid rewarding ignorance."
            ),
            "authoritative_optionality_claim_allowed": False,
        },
        {
            "id": "PICK-LIQUIDITY-CONTROL-001",
            "severity": "MEDIUM",
            "status": "HEURISTIC_STRATEGIC_PREMIUM_ACTIVE",
            "observation": (
                "Round-specific liquidity constants and the own-pick control bonus are strategically plausible "
                "but uncalibrated. They require transaction/decision evidence showing incremental value beyond "
                "the external pick market anchor and team-state utility."
            ),
            "authoritative_incremental_adjustment_claim_allowed": False,
        },
        {
            "id": "PICK-EMPIRICAL-READINESS-001",
            "severity": "HIGH",
            "status": "READY" if readiness_allowed else "NOT_READY_FOR_AUTHORITATIVE_CALIBRATION",
            "observation": (
                "The existing draft-outcome readiness gate is authoritative for whether league history is mature "
                "enough to fit a league-specific pick curve. Readiness is a prerequisite, not validation."
            ),
            "authoritative_empirical_claim_allowed": readiness_allowed,
        },
    ]

    required_markers = all(detected.values())
    registry_consistent = (
        governed.get("evidence_tier") == "ASSUMPTION_SENSITIVE_PROVISIONAL"
        and governed.get("authoritative_use") is False
        and bool(governed.get("bounds_required"))
    )

    payload = {
        "model_version": MODEL_VERSION,
        "purpose": "Audit future-pick economics without changing production valuation.",
        "production_behavior_changed": False,
        "policy": {
            "external_market_pick_values_are_anchor_not_training_labels": True,
            "fallback_values_must_remain_explicitly_provisional": True,
            "scenario_weights_are_not_probabilities_without_calibration": True,
            "forecast_uncertainty_is_not_automatically_positive_option_value": True,
            "market_liquidity_and_outcome_optionality_must_be_separated": True,
            "league_specific_pick_curve_requires_temporal_outcome_readiness": True,
            "promotion_requires_out_of_sample_improvement": True,
        },
        "runtime_markers": detected,
        "summary": {
            "all_expected_runtime_markers_detected": required_markers,
            "registry_consistent": registry_consistent,
            "pick_outcome_readiness_allows_authoritative_fit": readiness_allowed,
            "pick_quality_rows": len(picks),
            "comparable_multi_horizon_groups": comparable_groups,
            "exactly_invariant_multi_horizon_groups": invariant_groups,
        },
        "findings": findings,
    }

    (OUT / "future_pick_economics_audit.json").write_text(
        json.dumps(payload, indent=2), encoding="utf-8"
    )
    print(json.dumps(payload["summary"], indent=2))
    print(json.dumps(findings, indent=2))

    if not required_markers:
        raise SystemExit("Future-pick runtime changed: expected governed markers not detected")
    if not registry_consistent:
        raise SystemExit("PICK-MODEL-001 registry classification is inconsistent with runtime governance")


if __name__ == "__main__":
    main()
