#!/usr/bin/env python3
"""Consolidate coefficient provenance/recalibration research artifacts."""
from __future__ import annotations
import json
from collections import Counter
from pathlib import Path

ROOT=Path(__file__).resolve().parent.parent
DATA=ROOT/"data"
OUT=DATA/"model_validation"/"coefficient_recalibration_research_summary.json"

def load(path,default=None):
    try:return json.loads(path.read_text(encoding="utf-8"))
    except Exception:return default

def main():
    sources=[
      DATA/"model_governance"/"coefficient_provenance_seed_findings.json",
      DATA/"model_governance"/"coefficient_family_research_findings.json",
      DATA/"audit"/"behavioral_roster_parameter_provenance.json",
      DATA/"audit"/"trade_search_parameter_provenance.json",
      DATA/"audit"/"cross_asset_parameter_provenance.json",
    ]
    findings=[]
    source_status=[]
    for p in sources:
        obj=load(p,{}) or {}
        rows=obj.get("findings") or []
        findings.extend(rows)
        source_status.append({
            "path":p.relative_to(ROOT).as_posix(),
            "exists":p.exists(),
            "finding_count":len(rows)
        })

    by_evidence=Counter(str(x.get("evidence_classification") or "UNCLASSIFIED") for x in findings)
    by_action=Counter(str(x.get("recommended_action") or "UNCLASSIFIED") for x in findings)
    arbitrary=[x for x in findings if x.get("evidence_classification")=="LEGACY_ARBITRARY_HEURISTIC"]
    expert=[x for x in findings if x.get("evidence_classification")=="UNVALIDATED_EXPERT_PRIOR"]
    estimable=[
        x for x in findings
        if x.get("identifiability_class") in {"DIRECTLY_ESTIMABLE","SIMULATION_IDENTIFIABLE"}
    ]
    governed_priors=[
        x for x in findings
        if x.get("recommended_action")=="RETAIN_AS_GOVERNED_PRIOR"
    ]
    eliminate=[
        x for x in findings
        if x.get("recommended_action")=="ELIMINATE"
    ]
    diagnostic=[
        x for x in findings
        if x.get("recommended_action")=="DIAGNOSTIC_ONLY"
    ]

    readiness=load(DATA/"audit"/"strategy_outcome_readiness.json",{}) or {}
    sim=load(DATA/"audit"/"simulator_calibration_chain_audit.json",{}) or {}
    shadow=load(DATA/"audit"/"state_weight_shadow_research.json",{}) or {}
    panel=load(DATA/"model_validation"/"historical_trade_outcome_panel.json",{}) or {}
    promo=load(DATA/"audit"/"state_weight_promotion_readiness.json",{}) or {}
    recall=load(DATA/"audit"/"trade_search_hard_cutoff_recall.json",{}) or {}\n    cutoff_confirm=load(DATA/"audit"/"trade_search_hard_cutoff_shared_utility_confirmation.json",{}) or {}\n    channel_authority=load(DATA/"audit"/"effective_objective_channel_authority.json",{}) or {}\n    state_ident=load(DATA/"audit"/"state_weight_identifiability.json",{}) or {}\n    backup_opt=load(DATA/"audit"/"simulator_backup_assignment_optimality.json",{}) or {}\n    team_shock=load(DATA/"audit"/"simulator_team_shock_semantics.json",{}) or {}

    do_not_change=[
      {
        "family":"competitive-state objective weights",
        "reason":"incumbent is weak but no independent pristine temporal calibration target with uncertainty and downstream comparison exists yet",
        "status":"RETAIN_AS_GOVERNED_PRIOR"
      },
      {
        "family":"projection uncertainty distribution",
        "reason":"no archived contemporaneous player forecasts sufficient for residual calibration without look-ahead",
        "status":"RETAIN_CURRENT_PROXY_PENDING_RESIDUAL_ARCHIVE"
      },
      {
        "family":"Shared Decision Utility current-outcome median aggregator",
        "reason":"structurally defensible de-correlation choice; no held-out evidence yet supports a superior mapping",
        "status":"KEEP"
      },
      {
        "family":"future-pick market anchor",
        "reason":"external-anchor plus Simulator interpolation is more defensible than legacy tier cliffs; long-horizon calibration remains future work",
        "status":"KEEP"
      },
      {
        "family":"explicit QB position multiplier",
        "reason":"none is active and Superflex opportunity cost is already generated by league rules, lineup optimization and replacement depth",
        "status":"DO_NOT_INTRODUCE_WITHOUT_RESIDUAL_EVIDENCE"
      }
    ]

    potential_promotions=[]
    if (cutoff_confirm.get("summary") or {}).get("evidence_against_hard_cutoff_detected"):
        potential_promotions.append({
            "parameter":"trade search low-value/low-need hard exclusion",
            "candidate_action":"STRUCTURAL_ELIMINATION",
            "basis":"excluded GM3 discovery target(s) confirmed bilaterally non-negative by canonical Shared Decision Utility",
            "evidence_tier_of_incumbent":"LEGACY_ARBITRARY_HEURISTIC",
            "requires_separate_production_pr":True
        })

    report={
      "schema_version":"1.0",
      "model_version":"FSFFL-Coefficient-Recalibration-Research-Summary-1.0",
      "authority":"RESEARCH_SUMMARY_NON_AUTHORITATIVE",
      "production_behavior_changed":False,
      "source_status":source_status,
      "summary":{
        "finding_count":len(findings),
        "evidence_class_counts":dict(sorted(by_evidence.items())),
        "recommended_action_counts":dict(sorted(by_action.items())),
        "legacy_arbitrary_count":len(arbitrary),
        "unvalidated_expert_prior_count":len(expert),
        "empirically_or_simulation_estimable_count":len(estimable),
        "governed_prior_count":len(governed_priors),
        "structural_elimination_candidate_count":len(eliminate),
        "diagnostic_only_count":len(diagnostic),
        "production_promotions_made":0,
        "potential_separate_promotion_prs":len(potential_promotions)
      },
      "arbitrary_or_legacy_parameters":arbitrary,
      "unvalidated_expert_priors":expert,
      "estimable_parameters":estimable,
      "parameters_to_retain_as_governed_priors":governed_priors,
      "structural_elimination_candidates":eliminate,
      "diagnostic_only_parameters":diagnostic,
      "do_not_change_yet":do_not_change,
      "potential_evidence_supported_promotions":potential_promotions,
      "research_state":{
        "strategy_outcome_readiness":readiness.get("summary"),
        "simulator_chain":sim.get("summary"),
        "state_weight_shadow_sign_changes":shadow.get("sign_change_count"),
        "historical_trade_panel":panel.get("summary"),
        "state_weight_promotion":promo,
        "trade_search_hard_cutoff_recall":recall.get("summary"),\n        "trade_search_hard_cutoff_canonical_confirmation":cutoff_confirm.get("summary"),\n        "effective_objective_channel_authority":channel_authority.get("conclusions"),\n        "state_weight_identifiability":state_ident.get("summary"),\n        "simulator_backup_assignment_optimality":{\n            "passed":backup_opt.get("passed"),\n            "legacy_greedy_is_exact":backup_opt.get("legacy_greedy_is_exact"),
            "live_slot_scarcity_heuristic_active":backup_opt.get("live_slot_scarcity_heuristic_active"),
            "live_rule_derived_assignment_active":backup_opt.get("live_rule_derived_assignment_active"),\n            "grid_failure_count":backup_opt.get("grid_failure_count"),\n            "repair_status":backup_opt.get("repair_status"),
            "recommended_action":backup_opt.get("recommended_action"),\n        },\n        "simulator_team_shock_semantics":{\n            "passed":team_shock.get("passed"),\n            "calibration_status":team_shock.get("calibration_status"),\n            "recommended_action":team_shock.get("recommended_action"),\n        }
      },
      "plain_language_assessment":{
        "what_is_already_defensible":[
          "No separate final QB/Superflex multiplier is needed under current evidence.",
          "Points-to-wins and wins-to-title are generated by explicit simulation and league rules rather than fixed conversion coefficients.",
          "Market-tier scarcity and pick incremental hold premiums are structurally disabled where they would duplicate the market anchor.",
          "Manager-specific behavioral signals are adaptively shrunk and do not receive a separate final trade-value vote."
        ],
        "what_remains_weak":[
          "Competitive-state objective weights remain an unvalidated expert prior; nominal liquidity/resilience weights may have less final authority than their labels imply when those channels are structurally unauthorized.",
          "Projection uncertainty relies on realized-score dispersion proxies and fallback heuristics rather than archived forecast residuals.",
          "Several GM3 proactive-search coefficients and hard cutoffs are arbitrary and can create omission risk.",\n          "Simulator simultaneous-absence backup allocation has a deterministic greedy-assignment counterexample; structural exact-assignment repair is preferable to tuning slot-priority constants.",\n          "Same-team shock loadings have verified mathematical semantics but their magnitudes are not yet empirically calibrated from forecast residual covariance.",
          "Roster-cut prescreen coefficients are arbitrary where exact downstream plan evaluation is not used.",
          "Fallback future-pick tier/time/base constants remain provisional when external market coverage is insufficient."
        ],
        "why_no_production_weight_change_yet":"The audit has identified weak incumbents but has not manufactured precision. Production promotion remains separated from research and will occur only where stronger evidence clears the appropriate incumbent-tier standard."
      }
    }
    OUT.parent.mkdir(parents=True,exist_ok=True)
    OUT.write_text(json.dumps(report,indent=2)+"\n",encoding="utf-8")
    print(json.dumps(report["summary"],indent=2))

if __name__=="__main__":main()
